services:

  postgresql:
    image: postgres:16.4
    container_name: postgresql
    ports:
      - '5433:5432'
    restart: always
    environment:
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: tasks-db
    volumes:
      - postgres_db:/usr/pg/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USERNAME}" ]
      interval: 20s
      timeout: 5s
      retries: 3
    networks:
      - task-tracker

  zookeeper:
    image: bitnami/zookeeper:3.8.0
    container_name: zookeeper
    restart: on-failure
    ports:
      - '2181:2181'
    environment:
      ZOO_PORT: 2181
      ALLOW_ANONYMOUS_LOGIN: "yes"
    networks:
      - task-tracker

  kafka:
    image: bitnami/kafka:3.8.0
    container_name: kafka
    restart: on-failure
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://:29092,EXTERNAL://:9092
      KAFKA_TOPIC: EMAIL_SENDING_TASKS
      ALLOW_PLAINTEXT_LISTENER: yes
    networks:
      - task-tracker

  backend:
    restart: unless-stopped
    image: darkrubin/backend:latest
    container_name: app
    depends_on:
      - postgresql
      - kafka
    ports:
      - '8080:8080'
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/tasks-db
      SPRING_DATASOURCE_USERNAME: ${PG_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PG_PASSWORD}
      JWT_KEY: ${TOKEN_KEY}
    networks:
      - task-tracker

  frontend:
    restart: unless-stopped
    image: darkrubin/frontend:latest
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - task-tracker

  scheduler:
    restart: unless-stopped
    image: darkrubin/scheduler:latest
    container_name: scheduler
    depends_on:
      - backend
    ports:
      - "8880:8880"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/tasks-db
      SPRING_DATASOURCE_USERNAME: ${PG_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${PG_PASSWORD}
    networks:
      - task-tracker

  email-sender:
    restart: unless-stopped
    image: darkrubin/email-sender:latest
    container_name: email-sender
    depends_on:
      - kafka
    ports:
      - "8000:8000"
    environment:
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      SPRING_MAIL_HOST: ${MAIL_HOST}
    networks:
      - task-tracker

volumes:
  postgres_db:
    driver: local

networks:
  task-tracker:
    driver: bridge