spring:
  application:
    name: task-tracker-backend
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/tasks-db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
jwt:
  key: 53A73E5F1B4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75321855