name: main
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@latest
      - name: copy and run remote
        uses: D3rHase/ssh-command-action@latest
        with:
          host: ${{secrets.SSH_HOST}}
          user: ${{secrets.SSH_USER}}
          private_key: ${{secrets.SSH_PRIVATE_KEY}}
          command: |
            cd ${{ secrets.PROJECT_FOLDER }};
            git checkout main;
            git pull;
            docker-compose --file compose.yaml down;
            docker-compose --file compose.yaml up -d;
            docker system prune --all --force;
